/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\t-shirt_statics_19-v1.glb --transform 
Files: .\t-shirt_statics_19-v1.glb [69.76MB] > D:\Code\Fiverr\cloth-configurator\public\models\t-shirt_statics_19-v1-transformed.glb [3.48MB] (95%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/t-shirt_statics_19-v1-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <directionalLight intensity={1} decay={2} color="#cacaca" position={[1500, 3000, 1500]} rotation={[-1.107, 0.421, 0]} target={nodes.Light.target}>
        <primitive object={nodes.Light.target} position={[0, 0, -1]} />
      </directionalLight>
      <mesh geometry={nodes.Pattern_271376_Node.geometry} material={materials['FABRIC 1_FRONT_2456251']} />
    </group>
  )
}

useGLTF.preload('/t-shirt_statics_19-v1-transformed.glb')
