/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Tshirt_V10.glb -k -K -T -j -M 
Files: Tshirt_V10.glb [74.23MB] > /Users/hanan/Desktop/Work/cloth-configurator/public/models/Tshirt_V10-transformed.glb [60.29MB] (19%)
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/Tshirt_V10-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Pattern_740043_Node003"
          geometry={nodes.Pattern_740043_Node003.geometry}
          material={materials["fab.007"]}
          morphTargetDictionary={
            nodes.Pattern_740043_Node003.morphTargetDictionary
          }
          morphTargetInfluences={
            nodes.Pattern_740043_Node003.morphTargetInfluences
          }
        />
        <mesh
          name="Pattern_740043_Node001"
          geometry={nodes.Pattern_740043_Node001.geometry}
          material={materials["fab.007"]}
          morphTargetDictionary={
            nodes.Pattern_740043_Node001.morphTargetDictionary
          }
          morphTargetInfluences={
            nodes.Pattern_740043_Node001.morphTargetInfluences
          }
        />
        <mesh
          name="Pattern_740043_Node002"
          geometry={nodes.Pattern_740043_Node002.geometry}
          material={materials["fab.007"]}
          morphTargetDictionary={
            nodes.Pattern_740043_Node002.morphTargetDictionary
          }
          morphTargetInfluences={
            nodes.Pattern_740043_Node002.morphTargetInfluences
          }
        />
        <mesh
          name="Pattern_740043_Node004"
          geometry={nodes.Pattern_740043_Node004.geometry}
          material={materials["fab.007"]}
          morphTargetDictionary={
            nodes.Pattern_740043_Node004.morphTargetDictionary
          }
          morphTargetInfluences={
            nodes.Pattern_740043_Node004.morphTargetInfluences
          }
        />
        <mesh
          name="Pattern_740043_Node005"
          geometry={nodes.Pattern_740043_Node005.geometry}
          material={materials["fab.007"]}
          morphTargetDictionary={
            nodes.Pattern_740043_Node005.morphTargetDictionary
          }
          morphTargetInfluences={
            nodes.Pattern_740043_Node005.morphTargetInfluences
          }
        />
        <mesh
          name="Pattern_740043_Node006"
          geometry={nodes.Pattern_740043_Node006.geometry}
          material={materials["fab.007"]}
          morphTargetDictionary={
            nodes.Pattern_740043_Node006.morphTargetDictionary
          }
          morphTargetInfluences={
            nodes.Pattern_740043_Node006.morphTargetInfluences
          }
        />
        <mesh
          name="Pattern_740043_Node007"
          geometry={nodes.Pattern_740043_Node007.geometry}
          material={materials["fab.007"]}
          morphTargetDictionary={
            nodes.Pattern_740043_Node007.morphTargetDictionary
          }
          morphTargetInfluences={
            nodes.Pattern_740043_Node007.morphTargetInfluences
          }
        />
        <mesh
          name="Pattern_740043_Node008"
          geometry={nodes.Pattern_740043_Node008.geometry}
          material={materials["fab.007"]}
          morphTargetDictionary={
            nodes.Pattern_740043_Node008.morphTargetDictionary
          }
          morphTargetInfluences={
            nodes.Pattern_740043_Node008.morphTargetInfluences
          }
        />
        <mesh
          name="Pattern_740043_Node009"
          geometry={nodes.Pattern_740043_Node009.geometry}
          material={materials["fab.007"]}
          morphTargetDictionary={
            nodes.Pattern_740043_Node009.morphTargetDictionary
          }
          morphTargetInfluences={
            nodes.Pattern_740043_Node009.morphTargetInfluences
          }
        />
        <mesh
          name="Pattern_740043_Node010"
          geometry={nodes.Pattern_740043_Node010.geometry}
          material={materials["fab.007"]}
          morphTargetDictionary={
            nodes.Pattern_740043_Node010.morphTargetDictionary
          }
          morphTargetInfluences={
            nodes.Pattern_740043_Node010.morphTargetInfluences
          }
        />
        <mesh
          name="Pattern_740043_Node011"
          geometry={nodes.Pattern_740043_Node011.geometry}
          material={materials["fab.007"]}
          morphTargetDictionary={
            nodes.Pattern_740043_Node011.morphTargetDictionary
          }
          morphTargetInfluences={
            nodes.Pattern_740043_Node011.morphTargetInfluences
          }
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Tshirt_V10-transformed.glb");
