/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\t-shirt_statics_04.glb --transform 
Files: .\t-shirt_statics_04.glb [35.43MB] > D:\Code\Fiverr\cloth-configurator\public\models\t-shirt_statics_04-transformed.glb [2.45MB] (93%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export default function Model(props) {
  const { scene } = useGLTF("/models/t-shirt_statics_19-v1.glb");
  // const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  // const { nodes, materials , sce} = useGraph(clone);
  return <primitive object={scene} {...props} dispose={null} />;
}

useGLTF.preload("/models/t-shirt_statics_19-v1.glb");
