/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 t-shirt_anim.gltf --transform 
Files: t-shirt_anim.gltf [312.07MB] > /Users/hanan/Desktop/Work/cloth-configurator/public/models/t-shirt_anim-transformed.glb [187.3MB] (40%)
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/t-shirt_anim-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  console.log("actions", actions);
  React.useEffect(() => {
    actions["Cloth Animation"].play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="Pattern_271376_Node">
          <mesh
            name="Pattern_271376"
            geometry={nodes.Pattern_271376.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_271376.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_271376.morphTargetInfluences}
          />
          <mesh
            name="Pattern_271376_1"
            geometry={nodes.Pattern_271376_1.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_271376_1.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_271376_1.morphTargetInfluences}
          />
          <mesh
            name="Pattern_271376_2"
            geometry={nodes.Pattern_271376_2.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_271376_2.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_271376_2.morphTargetInfluences}
          />
        </group>
        <group name="Pattern_271377_Node">
          <mesh
            name="Pattern_271377"
            geometry={nodes.Pattern_271377.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_271377.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_271377.morphTargetInfluences}
          />
          <mesh
            name="Pattern_271377_1"
            geometry={nodes.Pattern_271377_1.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_271377_1.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_271377_1.morphTargetInfluences}
          />
          <mesh
            name="Pattern_271377_2"
            geometry={nodes.Pattern_271377_2.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_271377_2.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_271377_2.morphTargetInfluences}
          />
        </group>
        <group name="Pattern_238525_Node">
          <mesh
            name="Pattern_238525"
            geometry={nodes.Pattern_238525.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_238525.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_238525.morphTargetInfluences}
          />
          <mesh
            name="Pattern_238525_1"
            geometry={nodes.Pattern_238525_1.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_238525_1.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_238525_1.morphTargetInfluences}
          />
          <mesh
            name="Pattern_238525_2"
            geometry={nodes.Pattern_238525_2.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_238525_2.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_238525_2.morphTargetInfluences}
          />
        </group>
        <group name="Pattern_111264_Node">
          <mesh
            name="Pattern_111264"
            geometry={nodes.Pattern_111264.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_111264.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_111264.morphTargetInfluences}
          />
          <mesh
            name="Pattern_111264_1"
            geometry={nodes.Pattern_111264_1.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_111264_1.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_111264_1.morphTargetInfluences}
          />
          <mesh
            name="Pattern_111264_2"
            geometry={nodes.Pattern_111264_2.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_111264_2.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_111264_2.morphTargetInfluences}
          />
        </group>
        <group name="Pattern_740043_Node">
          <mesh
            name="Pattern_740043"
            geometry={nodes.Pattern_740043.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_740043.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_740043.morphTargetInfluences}
          />
          <mesh
            name="Pattern_740043_1"
            geometry={nodes.Pattern_740043_1.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_740043_1.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_740043_1.morphTargetInfluences}
          />
          <mesh
            name="Pattern_740043_2"
            geometry={nodes.Pattern_740043_2.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_740043_2.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_740043_2.morphTargetInfluences}
          />
        </group>
        <group name="Pattern_296730_Node">
          <mesh
            name="Pattern_296730"
            geometry={nodes.Pattern_296730.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_296730.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_296730.morphTargetInfluences}
          />
          <mesh
            name="Pattern_296730_1"
            geometry={nodes.Pattern_296730_1.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_296730_1.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_296730_1.morphTargetInfluences}
          />
          <mesh
            name="Pattern_296730_2"
            geometry={nodes.Pattern_296730_2.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_296730_2.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_296730_2.morphTargetInfluences}
          />
        </group>
        <group name="Pattern_296729_Node">
          <mesh
            name="Pattern_296729"
            geometry={nodes.Pattern_296729.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_296729.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_296729.morphTargetInfluences}
          />
          <mesh
            name="Pattern_296729_1"
            geometry={nodes.Pattern_296729_1.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_296729_1.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_296729_1.morphTargetInfluences}
          />
          <mesh
            name="Pattern_296729_2"
            geometry={nodes.Pattern_296729_2.geometry}
            material={materials["FABRIC 1_FRONT_80984"]}
            morphTargetDictionary={nodes.Pattern_296729_2.morphTargetDictionary}
            morphTargetInfluences={nodes.Pattern_296729_2.morphTargetInfluences}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/t-shirt_anim-transformed.glb");
